
USE MIA_Practica;

-- ******************************************************************
-- Se crea tabla temporal para la carga de datos desde el archivo CSV
-- ******************************************************************
DROP TEMPORARY TABLE IF EXISTS CSVTable;

CREATE TEMPORARY TABLE CSVTable(
idTemp INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE_VICTIMA VARCHAR(50) NOT NULL,
APELLIDO_VICTIMA VARCHAR(50) NOT NULL,
DIRECCION_VICTIMA VARCHAR(250) NOT NULL,
FECHA_PRIMERA_SOSPECHA DATETIME NOT NULL,
FECHA_CONFIRMACION DATETIME NOT NULL,
FECHA_MUERTE DATETIME DEFAULT NULL,
ESTADO_VICTIMA VARCHAR(50) NOT NULL,
NOMBRE_ASOCIADO VARCHAR(50),
APELLIDO_ASOCIADO VARCHAR(50),
FECHA_CONOCIO DATETIME,
CONTACTO_FISICO VARCHAR(25),
FECHA_INICIO_CONTACTO DATETIME,
FECHA_FIN_CONTACTO DATETIME,
NOMBRE_HOSPITAL VARCHAR(100),
DIRECCION_HOSPITAL VARCHAR(250),
UBICACION_VICTIMA VARCHAR(250),
FECHA_LLEGADA DATETIME,
FECHA_RETIRO DATETIME,
TRATAMIENTO VARCHAR(100),
EFECTIVIDAD INT,
FECHA_INICIO_TRATAMIENTO DATETIME,
FECHA_FIN_TRATAMIENTO DATETIME,
EFECTIVIDAD_EN_VICTIMA INT
);

-- ******************************************************************
-- Se carga datos del archivo CSV en la tabla temporal CSVTable
-- ******************************************************************

LOAD DATA LOCAL INFILE '/home/cristian/Descargas/GRAND_VIRUS_EPICENTER.csv' 
INTO TABLE CSVTable
FIELDS TERMINATED BY ';' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES(
NOMBRE_VICTIMA,
APELLIDO_VICTIMA,
DIRECCION_VICTIMA,
FECHA_PRIMERA_SOSPECHA,
FECHA_CONFIRMACION,
FECHA_MUERTE,
ESTADO_VICTIMA,
NOMBRE_ASOCIADO,
APELLIDO_ASOCIADO,
FECHA_CONOCIO,
CONTACTO_FISICO,
FECHA_INICIO_CONTACTO,
FECHA_FIN_CONTACTO,
NOMBRE_HOSPITAL,
DIRECCION_HOSPITAL,
UBICACION_VICTIMA,
FECHA_LLEGADA,
FECHA_RETIRO,
TRATAMIENTO,
EFECTIVIDAD,
FECHA_INICIO_TRATAMIENTO,
FECHA_FIN_TRATAMIENTO,
EFECTIVIDAD_EN_VICTIMA
);
-- SELECT * FROM CSVTable;








